spring:
  application:
    name: CourseService

server:
  port: 5000


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaservice-env.eba-fbdyeptj.ap-south-1.elasticbeanstalk.com/eureka/