zuul:
  routes:
    UserService:
      path: /UserService/**
      sensitiveHeaders: 
      url: http://userservice-env.eba-muuciyqz.ap-south-1.elasticbeanstalk.com/
    CourseService:
      path: /CourseService/**
      sensitiveHeaders: 
      url: http://courseservice-env.eba-s2dq6d2t.ap-south-1.elasticbeanstalk.com/

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice-env.eba-fbdyeptj.ap-south-1.elasticbeanstalk.com/eureka/

server:
  port: 5000

spring:
  application:
    name: ZuulService