zuul:
  routes:
    UserService:
      path: /UserService/**
      sensitiveHeaders: 
      url: http://localhost:8082
    CourseService:
      path: /CourseService/**
      sensitiveHeaders: 
      url: http://localhost:8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8765

spring:
  application:
    name: ZuulService